name: attunet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gdal
  - rasterio
  - rioxarray
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - tensorflow-macos==2.8
      - keras==2.8
      - tensorflow-metal
      - pillow
      - segmentation-models
      - rarfile
      - pyunpack
      - patool
      - pathlib
