name: deforestation
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cython=0.29.37=py39hf3050f2_0
  - debugpy=1.8.16=py39hd866990_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - hdf5=1.10.6=nompi_h0fc092c_1114
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.20.1=h127bd45_0
  - libblas=3.11.0=2_h51639a9_openblas
  - libcblas=3.11.0=2_hb0561ab_openblas
  - libcurl=7.87.0=hbe9bab4_0
  - libcxx=21.1.6=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libgcc=15.2.0=hcbb3090_14
  - libgfortran=15.2.0=h07b0088_14
  - libgfortran5=15.2.0=hdae7583_14
  - liblapack=3.11.0=2_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnghttp2=1.51.0=hd184df1_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.10.0=hb80f160_3
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=21.1.6=h4a912ad_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=1.1.1w=h53f4e23_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39hf3bc14e_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.9.15=h2d96c93_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=8_cp39
  - pyzmq=27.0.2=py39h6c7bd39_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py39hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.46.0=h5838104_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.2=py39he7485ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfb2fe0b_6
  - pip:
      - absl-py==2.3.1
      - affine==2.4.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - easyprocess==1.1
      - efficientnet==1.0.0
      - entrypoint2==1.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.7.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - idna==3.11
      - image-classifiers==1.0.0
      - imageio==2.5.0
      - imgaug==0.4.0
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - keras==2.15.0
      - keras-applications==1.0.8
      - keras-segmentation==0.3.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - ml-dtypes==0.2.0
      - networkx==3.2.1
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opencv-python==4.7.0.72
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.5
      - pyproj==3.6.1
      - pytz==2025.2
      - pyunpack==0.3
      - pywavelets==1.6.0
      - rarfile==4.2
      - rasterio==1.4.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rioxarray==0.15.0
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - segmentation-models==1.0.1
      - shapely==2.0.7
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.15.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tqdm==4.67.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.4
      - wrapt==1.14.2
      - xarray==2024.7.0
prefix: /opt/anaconda3/envs/deforestation
